### ISSUE TITLE
Ubuntu 16.04.3 fails to build

### ISSUE THREAD

**Issue by crsleeth** [GrimKriegor/TES3MP-deploy#10]
Ubuntu 16.04.3 fails to deploy at this step:
`/home/ryan/TESMP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp: In member function ‘void mwmp::DedicatedActor::equipItem(std::__cxx11::string, int)’: /home/ryan/TESMP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp:239:28: error: use of ‘ptr’ before deduction of ‘auto’ for (const auto &ptr : ptr.getClass().getInventoryStore(ptr)) ^ /home/ryan/TESMP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp:239:61: error: use of ‘ptr’ before deduction of ‘auto’ for (const auto &ptr : ptr.getClass().getInventoryStore(ptr)) ^ apps/openmw/CMakeFiles/tes3mp.dir/build.make:6038: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/mwmp/DedicatedActor.cpp.o' failed make[2]: *** [apps/openmw/CMakeFiles/tes3mp.dir/mwmp/DedicatedActor.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs.... CMakeFiles/Makefile2:501: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/all' failed make[1]: *** [apps/openmw/CMakeFiles/tes3mp.dir/all] Error 2 Makefile:127: recipe for target 'all' failed make: *** [all] Error 2`

**Comment by GrimKriegor** [comment]
Hello and thanks for reporting.

You can find an explanation and possible solution [here.](https://github.com/GrimKriegor/TES3MP-deploy/issues/8#issuecomment-325322868)

It is entirely my fault for not having done something about this yet.

**Comment by GrimKriegor** [comment]
Fixed by https://github.com/GrimKriegor/TES3MP-deploy/commit/1742a63774caad31b559b12a1ca38bc68ca8d25c
