### ISSUE TITLE
Support for the TES3MP rewrite

### ISSUE THREAD

**Issue by GrimKriegor** [GrimKriegor/TES3MP-deploy#15]
Since TES3MP 0.8.0 was the stage for major rewrites namely on the server side scripting API, dependencies and build methods are sure to change.

Please discuss, propose changes or pull requests on the tes3mp-0.8 branch.

https://github.com/GrimKriegor/TES3MP-deploy/tree/tes3mp-rewrite

**Comment by testman42** [comment]
You bastard, you just recycled this issue for support with 0.8 now that you have 0.7 branch nicely working :laughing:

**Comment by GrimKriegor** [comment]
@testman42 Ahahah. Actually this issue is still about the same 'version', that of the rewrite, it was the upstream that decided to rename it from 0.7 to 0.8 as you know.

**Comment by GrimKriegor** [comment]
Closing this for now as no TES3MP rewrite seems to be currently in development.
