### ISSUE TITLE
tes3mp-deploy.sh: 562: tes3mp-deploy.sh: [[: not found

### ISSUE THREAD

**Issue by UltraMCPL** [GrimKriegor/TES3MP-deploy#20]
>> Switching to the STABLE branch.
No local changes to save
Already up-to-date.
Already on '0.6.2'
Your branch is up-to-date with 'origin/0.6.2'.
tes3mp-deploy.sh: 562: tes3mp-deploy.sh: [[: not found
tes3mp-deploy.sh: 562: tes3mp-deploy.sh: stable: not found
tes3mp-deploy.sh: 567: [: stable: unexpected operator
-e
Checking out stable
No local changes to save
Already up-to-date.
error: pathspec 'stable' did not match any file(s) known to git.

**Comment by UltraMCPL** [comment]
xD your code is shit

**Comment by GrimKriegor** [comment]
I will forget your insult and your huge spam of issues and give you the benefit of the doubt, do not squander it and keep your issue on this one.

How are you running the script? It looks like you are using `sh` to run it.

**Comment by UltraMCPL** [comment]
Eh... I was wondering is opening more than 1 ticket will annoy anyone.

Yes I'm running it from sh on Debian jessie, why? Also I do not really know what packages and from what sources I should have preinstalled.

**Comment by GrimKriegor** [comment]
Ever seen a [shebang](https://github.com/GrimKriegor/TES3MP-deploy/blob/master/tes3mp-deploy.sh#L1)?

You are running the script with the wrong interpreter, either execute it directly or redundantly use the right one.

This script isn't meant for newbies, but rather for automating the packaging process, use the prebuilt binaries provided in the [download page](https://github.com/TES3MP/openmw-tes3mp/releases) like everyone else.

Opening more than one issue isn't annoying but acting like an insecure teenager is.
