### ISSUE TITLE
Credits file checksum

### ISSUE THREAD

**Issue by testman42** [GrimKriegor/TES3MP-deploy#28]
It is one of latest functions added to 0.7.0
```
$ ./tes3mp-server 
Loading settings file: ./tes3mp-server-default.cfg
Loading settings file: /home/leon/.config/openmw/tes3mp-server.cfg
TES3MP dedicated server 0.7.0-alpha (Linux 64-bit)
Protocol version: 7
Commit hash: 837c5369c0
------------------------------------------------------------
[2018-07-19 18:44:00] [FATAL]: The server is shutting down
- To respect the hard work that has gone into creating TES3MP, you are
required to keep an unmodified tes3mp-credits file corresponding to this
version of the code in the same folder as this executable. It can have either
an .md or a .txt extension.
```
I think that server executable is just confused about file's location, as with TES3MP-Deploy it is in `/code/tes3mp-credits.md` instead of server's directory (or whatever [this](https://github.com/TES3MP/openmw-tes3mp/blob/2e227c7af5a75574451c5c1dee49ead7179561f4/apps/openmw/main.cpp#L232) translates to)

**Comment by testman42** [comment]
Copying / moving file to `build` seems to be a good workaround.

**Comment by GrimKriegor** [comment]
Nice find.

Initially, this whole creditation issue had been dealt with at packaging.
https://github.com/GrimKriegor/TES3MP-deploy/commit/0bbe2b7e098809c883dd17ac9b0fd5da0ed43f52

I absolutely forgot there are still people using this to compile their own clients.
Should be fixed now.
https://github.com/GrimKriegor/TES3MP-deploy/commit/8698cf8d5f3e9dca1f14147bce89ccc8f1383844

Thanks.
