### ISSUE TITLE
tes3mp-server fails to compile on an Odroid xu4 running Debian Stretch

### ISSUE THREAD

**Issue by isthisme** [GrimKriegor/TES3MP-deploy#31]
I get this error near the end of the compilation whenever I run the command `./tes3mp-deploy.sh --install --server-only`:

LangLua.cpp:(.text._ZN1CILj599EE2FnEP14LuaFuctionData[_ZN1CILj599EE2FnEP14LuaFuctionData]+0x34): undefined reference to `F_<599u>::F'
CMakeFiles/tes3mp-server.dir/Script/LangLua/LangLua.cpp.o: In function `C<600u>::Fn(LuaFuctionData*)':
LangLua.cpp:(.text._ZN1CILj600EE2FnEP14LuaFuctionData[_ZN1CILj600EE2FnEP14LuaFuctionData]+0x34): undefined reference to `F_<600u>::F'
collect2: error: ld returned 1 exit status
apps/openmw-mp/CMakeFiles/tes3mp-server.dir/build.make:1167: recipe for target 'tes3mp-server' failed
make[2]: *** [tes3mp-server] Error 1
CMakeFiles/Makefile2:294: recipe for target 'apps/openmw-mp/CMakeFiles/tes3mp-server.dir/all' failed
make[1]: *** [apps/openmw-mp/CMakeFiles/tes3mp-server.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Sorry I'm having trouble pasting this error into a proper comment.

**Comment by GrimKriegor** [comment]
Hello there, thanks for reporting.

We have been trying to sort out this issue with TES3MP upstream, will let you know whenever it's solved.

In the meanwhile, will this latest working official build suffice?

https://github.com/TES3MP/openmw-tes3mp/releases/download/0.7.0-alpha/tes3mp-server-GNU+Linux-armv7l-release-0.7.0-alpha-343dd8b5ea-95bd2bc93d.tar.gz

**Comment by Koncord** [comment]
What GCC version do you use?

**Comment by isthisme** [comment]
> What GCC version do you use?

The default in Stretch, 6.3

**Comment by GrimKriegor** [comment]
Fixed upstream.
https://github.com/TES3MP/openmw-tes3mp/commit/0df32acccab584579b04b6e3dc9277aea2a6a15e
