### ISSUE TITLE
CallFF dependancy build failing [Archlinux]

### ISSUE THREAD

**Issue by 1338** [GrimKriegor/TES3MP-deploy#32]
Log file tes3mp-deploy: https://pastebin.com/DUXhB1NP
It doesn't seem your fault though as CallFF fails on it's own too: https://pastebin.com/MdDWuiB0
Just thought you should know, so you can bug Koncord.

**Comment by GrimKriegor** [comment]
Thanks for reporting.

Should be fixed now. https://github.com/GrimKriegor/TES3MP-deploy/commit/d4ef7381303f0b74b5d93dcde2f8333d9cb1f018

However, months ago, there were some issues when building with newer versions of GCC, including the ones available in the Arch based distros.

Using `--container` should act as a workaround if that is still the case.

**Comment by 1338** [comment]
Oh interestingly I needed to define CXX to g++ (I'm guessing it was defaulting to clang which didn't have LLVM backend because it wasn't installed. Whoops)
Thanks for the quick response able to compile now.
