### ISSUE TITLE
Upgrade TES3MP_STABLE_VERSION to 0.7.1

### ISSUE THREAD

**Issue by ghost** [GrimKriegor/TES3MP-deploy#33]
Hi @GrimKriegor!
Isn't it a time to update script to point to 0.7.1 tes3mp version?

**Comment by GrimKriegor** [comment]
@gnidorah hey there!
You mean the [TES3MP_STABLE_VERSION](https://github.com/GrimKriegor/TES3MP-deploy/blob/master/tes3mp-deploy.sh#L7) variable, right?
We usually update it every time a stable version is released, unfortunately 0.7.1 is still in development and hasn't been released yet.

**Comment by ghost** [comment]
@GrimKriegor Ah, thank you! So 0.7.1 branch will become stable as soon as there will be 0.7.1 release issued?

**Comment by GrimKriegor** [comment]
Indeed.
The ETA for 0.7.1, I am told, should be, as always, SOON™, ahah.
