### ISSUE TITLE
Debian Stretch 9 kernel panics connecting to download assets

### ISSUE THREAD

**Issue by crsleeth** [GrimKriegor/TES3MP-deploy#9]
Might be a fault of my hardware and running in ESXI but my Debian Stretch install kernel panics at this step: 
![debian](https://user-images.githubusercontent.com/13802587/30005890-38c24e14-90ba-11e7-9463-3dfc888bdbe2.PNG)

**Comment by GrimKriegor** [comment]
That's extremely strange.

Does it also panic when doing that command manually?

    wget https://github.com/zdevito/terra/releases/download/release-2016-02-26/terra-Linux-x86_64-2fa8d0a.zip -O terra.zip

**Comment by crsleeth** [comment]
I'll close the issue although I never investigated it further I'm pretty sure it was my hardware or ESXi at fault--it works well on Ubuntu running on Proxmox.
